{
 "title": "Home",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Temperature",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "Salon" }
     ]
    }
   ]
  },
  {
   "title": "Current humidity level",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sensors",
     "query": "SELECT mean(\"humidity\") FROM \"sensors\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rooms temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "sensors",
     "query": "SELECT \"temperature\" AS \"Temperature\" FROM \"sensors\" WHERE $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       { "params": [ "Temperature" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity levels",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}